import type { PUMP_ERROR__ACCOUNT_TYPE_NOT_SUPPORTED, PUMP_ERROR__ALL_FEE_RECIPIENTS_SHOULD_BE_NON_ZERO, PUMP_ERROR__ALL_ZEROS_WITHDRAW_AUTHORITY, PUMP_ERROR__ALREADY_INITIALIZED, PUMP_ERROR__BONDING_CURVE_COMPLETE, PUMP_ERROR__BONDING_CURVE_NOT_COMPLETE, PUMP_ERROR__BUY_ZERO_AMOUNT, PUMP_ERROR__CREATOR_SHOULD_NOT_BE_ZERO, PUMP_ERROR__DISABLED_MIGRATE, PUMP_ERROR__DISABLED_WITHDRAW, PUMP_ERROR__DIVISION_BY_ZERO, PUMP_ERROR__FEE_BASIS_POINTS_GREATER_THAN_MAXIMUM, PUMP_ERROR__INITIAL_REAL_TOKEN_RESERVES_SHOULD_BE_LESS_THAN_TOKEN_TOTAL_SUPPLY, PUMP_ERROR__INITIAL_VIRTUAL_TOKEN_RESERVES_SHOULD_BE_GREATER_THAN_INITIAL_REAL_TOKEN_RESERVES, PUMP_ERROR__INVALID_CREATOR, PUMP_ERROR__MINT_DOES_NOT_MATCH_BONDING_CURVE, PUMP_ERROR__NEW_SIZE_SHOULD_BE_GREATER_THAN_CURRENT_SIZE, PUMP_ERROR__NOT_AUTHORIZED, PUMP_ERROR__NOT_ENOUGH_REMAINING_ACCOUNTS, PUMP_ERROR__NOT_ENOUGH_TOKENS_TO_BUY, PUMP_ERROR__NOT_ENOUGH_TOKENS_TO_SELL, PUMP_ERROR__NOT_INITIALIZED, PUMP_ERROR__OVERFLOW, PUMP_ERROR__POOL_MIGRATION_FEE_SHOULD_BE_GREATER_THAN_CREATOR_FEE_PLUS_MAX_MIGRATE_FEES, PUMP_ERROR__POOL_MIGRATION_FEE_SHOULD_BE_LESS_THAN_FINAL_REAL_SOL_RESERVES, PUMP_ERROR__SELL_ZERO_AMOUNT, PUMP_ERROR__TOO_LITTLE_SOL_RECEIVED, PUMP_ERROR__TOO_MUCH_SOL_REQUIRED, PUMP_ERROR__TRUNCATION, PUMP_ERROR__UNSORTED_NOT_UNIQUE_FEE_RECIPIENTS, PUMP_ERROR__WITHDRAW_TOO_FREQUENT } from './constants'

export type PumpError =
    | typeof PUMP_ERROR__ACCOUNT_TYPE_NOT_SUPPORTED
    | typeof PUMP_ERROR__ALL_FEE_RECIPIENTS_SHOULD_BE_NON_ZERO
    | typeof PUMP_ERROR__ALL_ZEROS_WITHDRAW_AUTHORITY
    | typeof PUMP_ERROR__ALREADY_INITIALIZED
    | typeof PUMP_ERROR__BONDING_CURVE_COMPLETE
    | typeof PUMP_ERROR__BONDING_CURVE_NOT_COMPLETE
    | typeof PUMP_ERROR__BUY_ZERO_AMOUNT
    | typeof PUMP_ERROR__CREATOR_SHOULD_NOT_BE_ZERO
    | typeof PUMP_ERROR__DISABLED_MIGRATE
    | typeof PUMP_ERROR__DISABLED_WITHDRAW
    | typeof PUMP_ERROR__DIVISION_BY_ZERO
    | typeof PUMP_ERROR__FEE_BASIS_POINTS_GREATER_THAN_MAXIMUM
    | typeof PUMP_ERROR__INITIAL_REAL_TOKEN_RESERVES_SHOULD_BE_LESS_THAN_TOKEN_TOTAL_SUPPLY
    | typeof PUMP_ERROR__INITIAL_VIRTUAL_TOKEN_RESERVES_SHOULD_BE_GREATER_THAN_INITIAL_REAL_TOKEN_RESERVES
    | typeof PUMP_ERROR__INVALID_CREATOR
    | typeof PUMP_ERROR__MINT_DOES_NOT_MATCH_BONDING_CURVE
    | typeof PUMP_ERROR__NEW_SIZE_SHOULD_BE_GREATER_THAN_CURRENT_SIZE
    | typeof PUMP_ERROR__NOT_AUTHORIZED
    | typeof PUMP_ERROR__NOT_ENOUGH_REMAINING_ACCOUNTS
    | typeof PUMP_ERROR__NOT_ENOUGH_TOKENS_TO_BUY
    | typeof PUMP_ERROR__NOT_ENOUGH_TOKENS_TO_SELL
    | typeof PUMP_ERROR__NOT_INITIALIZED
    | typeof PUMP_ERROR__OVERFLOW
    | typeof PUMP_ERROR__POOL_MIGRATION_FEE_SHOULD_BE_GREATER_THAN_CREATOR_FEE_PLUS_MAX_MIGRATE_FEES
    | typeof PUMP_ERROR__POOL_MIGRATION_FEE_SHOULD_BE_LESS_THAN_FINAL_REAL_SOL_RESERVES
    | typeof PUMP_ERROR__SELL_ZERO_AMOUNT
    | typeof PUMP_ERROR__TOO_LITTLE_SOL_RECEIVED
    | typeof PUMP_ERROR__TOO_MUCH_SOL_REQUIRED
    | typeof PUMP_ERROR__TRUNCATION
    | typeof PUMP_ERROR__UNSORTED_NOT_UNIQUE_FEE_RECIPIENTS
    | typeof PUMP_ERROR__WITHDRAW_TOO_FREQUENT
